### ISSUE TITLE
[Feature] Add `--add-rank-lineage` to `taxpasta merge` and `taxpasta standardise`

### ISSUE THREAD

**Issue by MajoroMask** [taxprofiler/taxpasta#126]
### Checklist

- [X] There are [no similar issues or pull requests](https://github.com/taxprofiler/taxpasta/issues) for this yet.

### Description of feature

Hi @jfy133 and all. 

In taxpasta output file, we have:

- tax id by default, `--add-name` to show tax name, and `--add-rank` to show tax rank.
- `--add-id-lineage` to lineage tax ids, `--add-lineage` to add lineage tax names.

We are missing the lineage rank info for now.

### Solution

Adding a `--add-rank-lineage` to show lineage tax rank information looks natural to me. 

### Alternatives

I've wrote a R script to generate this kind of information from a kraken2 reference inspect file ([kraken2 inspect docs](https://github.com/DerrickWood/kraken2/blob/master/docs/MANUAL.markdown#inspecting-a-kraken-2-databases-contents)) before, so I think this is doable via NCBI taxdump.

**Comment by Midnighter** [comment]
Reasonable request, indeed. I'll try to implement it soon. Although I'm going on vacation soon.

**Comment by maxibor** [comment]
It's already in taxopy :)
