### ISSUE TITLE
Support tool: MetaPhlAn3

### ISSUE THREAD

**Issue by jfy133** [taxprofiler/taxpasta#14]
### Checklist

- [x] There are [no similar issues or pull requests](https://github.com/taxprofiler/taxpasta/issues) for this yet.

## Describe the solution you would like.

We should support the metagenomic classifier MetaPhlAn3

**Comment by sofstam** [comment]
Is metaphlan missing from https://github.com/taxprofiler/taxpasta/tree/dev/tests/unit/infrastructure/application ?
