### ISSUE TITLE
Add support for new metagenomic tool: MALT

### ISSUE THREAD

**Issue by maxibor** [taxprofiler/taxpasta#15]
MALT: [uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/informatik/lehrstuehle/algorithms-in-bioinformatics/software/malt](https://uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/informatik/lehrstuehle/algorithms-in-bioinformatics/software/malt/)
Default output:
RMA6 file, which is transformed in gzip compressed text file using rma2info https://github.com/nf-core/taxprofiler/blob/dev/modules/nf-core/modules/megan/rma2info/meta.yml

**Comment by jfy133** [comment]
Also .MEGAN 'summary' files are also text based

**Comment by maxibor** [comment]
rma2info usage for taxonomy:

```bash
rma2info \
    -i test.rma6 \ # output file of malt
    -o test.txt.gz \ # the rma2info output we're parsing with taxpasta
    -es test.megan \ # the megan output file
    -c2c Taxonomy # cluster the reads by taxid
```
