### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by maxibor** [taxprofiler/taxpasta#22]
For easing the task of adding new taxonomic profiler and for TDD, tests would be nice to have.

@Midnighter Do you want to create a base example of tests for Kraken2 ?

**Comment by Midnighter** [comment]
I actually just pushed some tests yesterday in #20 😉 

I just started to adapt #19 to include a description for that, too.

**Comment by Midnighter** [comment]
Feel free to re-open if you consider this point not addressed yet.
