### ISSUE TITLE
Rename MALT to MEGAN6

### ISSUE THREAD

**Issue by jfy133** [taxprofiler/taxpasta#45]
#### Problem description

Even though we are using MALT in taxprofiler, this actually produces a RMA6 format file which is actually for use in MEGAN6.

The current input files that we parse here in taxpasta are actually from a MEGAN6 utility tool called rma2info.

I propose we rename all references to MALT to MEGAN6, as this more accurately describes where you get the data file type from. Furhtermore MEGAN6 is much more widely used than MALT (which stands for 'Megan ALignment Tool' btw), so would be more accessible from that point of view.

**Comment by Midnighter** [comment]
Sounds reasonable to me. Do you have an opinion @maxibor ?
