### ISSUE TITLE
Metaphlan3 output contains reads classified as taxid '-1' [BUG] 

### ISSUE THREAD

**Issue by prototaxites** [taxprofiler/taxpasta#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Apparently this shouldn't happen! Values for the taxid are either 0 or 100000000 in all cases.

Occured when running taxpasta through nf-core/taxprofiler - I don't have an independent taxpasta installation.

### Code sample

nextflow run nf-core/taxprofiler \
    -resume \
    -r 1.0.0 \
    -profile scw \
    --input "inputs/samples.csv" \
    --databases "inputs/databases.csv" \
    --preprocessing_qc_tool "falco" \
    --run_kraken2 \
    --run_metaphlan3 \
    --run_motus \
    --outdir "results/"

### Environment

N/A

**Comment by Midnighter** [comment]
The original metaphlan output is in fractions, so 0 for not identified at all or 1 for only one taxon identified. We multiply the fractions by 10^6 in order to obtain integer values. That's why you get those results.
